import React, { Component } from 'react'

import Select from 'react-select';


class LocationSearch extends Component {
    constructor(props) {
        super(props);
        this.state = {
            Ville: "",
            list: [
                { label: " Aachech     ", value: "  Aachech     " },
                { label: " Agareb     ", value: "  Agareb     " },
                { label: " Aïn Djeloula     ", value: "  Aïn Djeloula     " },
                { label: " Aïn Draham     ", value: "  Aïn Draham     " },
                { label: " Akouda     ", value: "  Akouda     " },
                { label: " Al Ahouaz - El Assouda     ", value: "  Al Ahouaz - El Assouda     " },
                { label: " Amdoun     ", value: "  Amdoun     " },
                { label: " Amiret El Fhoul     ", value: "  Amiret El Fhoul     " },
                { label: " Amiret Hajjaj     ", value: "  Amiret Hajjaj     " },
                { label: " Amiret Touazra     ", value: "  Amiret Touazra     " },
                { label: " Aousja     ", value: "  Aousja     " },
                { label: " Ariana     ", value: "  Ariana     " },
                { label: " Azmour     ", value: "  Azmour     " },
                { label: " Bargou     ", value: "  Bargou     " },
                { label: " Béja     ", value: "  Béja     " },
                { label: " Bekalta     ", value: "  Bekalta     " },
                { label: " Belkhir     ", value: "  Belkhir     " },
                { label: " Bembla     ", value: "  Bembla     " },
                { label: " Ben Arous     ", value: "  Ben Arous     " },
                { label: " Ben Gardane     ", value: "  Ben Gardane     " },
                { label: " Beni Hassen     ", value: "  Beni Hassen     " },
                { label: " Béni Khalled     ", value: "  Béni Khalled     " },
                { label: " Beni Khedache     ", value: "  Beni Khedache     " },
                { label: " Béni Khiar     ", value: "  Béni Khiar     " },
                { label: " Beni M'Tir	                                                   ", value: "  Beni M'Tir	                                                   " },
                { label: " Bennane - Bodheur     ", value: "  Bennane - Bodheur     " },
                { label: " Bir Ali Ben Khalifa     ", value: "  Bir Ali Ben Khalifa     " },
                { label: " Bir El Hafey     ", value: "  Bir El Hafey     " },
                { label: " Bir Lahmar     ", value: "  Bir Lahmar     " },
                { label: " Bir Mcherga     ", value: "  Bir Mcherga     " },
                { label: " Bizerte     ", value: "  Bizerte     " },
                { label: " Borj El Amri     ", value: "  Borj El Amri     " },
                { label: " Bou Arada     ", value: "  Bou Arada     " },
                { label: " Bou Argoub     ", value: "  Bou Argoub     " },
                { label: " Bou Hajla     ", value: "  Bou Hajla     " },
                { label: " Bou Merdes     ", value: "  Bou Merdes     " },
                { label: " Bou Mhel el - Bassatine     ", value: "  Bou Mhel el - Bassatine     " },
                { label: " Bou Salem     ", value: "  Bou Salem     " },
                { label: " Bouchemma     ", value: "  Bouchemma     " },
                { label: " Bouficha     ", value: "  Bouficha     " },
                { label: " Bouhjar     ", value: "  Bouhjar     " },
                { label: " Carthage     ", value: "  Carthage     " },
                { label: " Cebbala Ouled Asker     ", value: "  Cebbala Ouled Asker     " },
                { label: " Chebba     ", value: "  Chebba     " },
                { label: " Chebika     ", value: "  Chebika     " },
                { label: " Chenini Nahal     ", value: "  Chenini Nahal     " },
                { label: " Cherahil     ", value: "  Cherahil     " },
                { label: " Chihia     ", value: "  Chihia     " },
                { label: " Chorbane     ", value: "  Chorbane     " },
                { label: " Dahmani     ", value: "  Dahmani     " },
                { label: " Dar Allouch     ", value: "  Dar Allouch     " },
                { label: " Dar Chaâbane     ", value: "  Dar Chaâbane     " },
                { label: " Degache     ", value: "  Degache     " },
                { label: " Dehiba     ", value: "  Dehiba     " },
                { label: " Den Den     ", value: "  Den Den     " },
                { label: " Djebel Oust     ", value: "  Djebel Oust     " },
                { label: " Djedeida     ", value: "  Djedeida     " },
                { label: " Djerba - Ajim     ", value: "  Djerba - Ajim     " },
                { label: " Djerba - Houmt Souk     ", value: "  Djerba - Houmt Souk     " },
                { label: " Djerba - Midoun     ", value: "  Djerba - Midoun     " },
                { label: " Douar Hicher     ", value: "  Douar Hicher     " },
                { label: " Douz     ", value: "  Douz     " },
                { label: " Echrarda     ", value: "  Echrarda     " },
                { label: " El Aïn     ", value: "  El Aïn     " },
                { label: " El Alâa     ", value: "  El Alâa     " },
                { label: " El Alia     ", value: "  El Alia     " },
                { label: " El Amra     ", value: "  El Amra     " },
                { label: " El Aroussa     ", value: "  El Aroussa     " },
                { label: " El Ayoun     ", value: "  El Ayoun     " },
                { label: " El Batan     ", value: "  El Batan     " },
                { label: " El Bradâa     ", value: "  El Bradâa     " },
                { label: " El Fahs     ", value: "  El Fahs     " },
                { label: " El Ghnada     ", value: "  El Ghnada     " },
                { label: " El Golâa     ", value: "  El Golâa     " },
                { label: " El Guettar     ", value: "  El Guettar     " },
                { label: " El Hamma     ", value: "  El Hamma     " },
                { label: " El Hamma du Jérid     ", value: "  El Hamma du Jérid     " },
                { label: " El Haouaria     ", value: "  El Haouaria     " },
                { label: " El Hencha     ", value: "  El Hencha     " },
                { label: " El Jem     ", value: "  El Jem     " },
                { label: " El Krib     ", value: "  El Krib     " },
                { label: " El Ksar     ", value: "  El Ksar     " },
                { label: " El Ksour     ", value: "  El Ksour     " },
                { label: " El Maâgoula     ", value: "  El Maâgoula     " },
                { label: " El Maâmoura     ", value: "  El Maâmoura     " },
                { label: " El Masdour     ", value: "  El Masdour     " },
                { label: " El Mida     ", value: "  El Mida     " },
                { label: " El Mourouj     ", value: "  El Mourouj     " },
                { label: " Enfida     ", value: "  Enfida     " },
                { label: " Ennasr     ", value: "  Ennasr     " },
                { label: " Essaïda     ", value: "  Essaïda     " },
                { label: " Essouassi     ", value: "  Essouassi     " },
                { label: " Ezzahra     ", value: "  Ezzahra     " },
                { label: " Ezzouhour     ", value: "  Ezzouhour     " },
                { label: " Ezzouhour     ", value: "  Ezzouhour     " },
                { label: " Faouar     ", value: "  Faouar     " },
                { label: " Fériana     ", value: "  Fériana     " },
                { label: " Fernana     ", value: "  Fernana     " },
                { label: " Fouchana     ", value: "  Fouchana     " },
                { label: " Foussana     ", value: "  Foussana     " },
                { label: " Gaâfour     ", value: "  Gaâfour     " },
                { label: " Gabès     ", value: "  Gabès     " },
                { label: " Gafsa     ", value: "  Gafsa     " },
                { label: " Ghannouch     ", value: "  Ghannouch     " },
                { label: " Ghar El Melh     ", value: "  Ghar El Melh     " },
                { label: " Ghardimaou     ", value: "  Ghardimaou     " },
                { label: " Ghezala     ", value: "  Ghezala     " },
                { label: " Ghomrassen     ", value: "  Ghomrassen     " },
                { label: " Goubellat     ", value: "  Goubellat     " },
                { label: " Graïba     ", value: "  Graïba     " },
                { label: " Gremda     ", value: "  Gremda     " },
                { label: " Grombalia     ", value: "  Grombalia     " },
                { label: " Hadjeb     ", value: "  Hadjeb     " },
                { label: " Haffouz     ", value: "  Haffouz     " },
                { label: " Haïdra     ", value: "  Haïdra     " },
                { label: " Hajeb El Ayoun     ", value: "  Hajeb El Ayoun     " },
                { label: " Hammam Chott     ", value: "  Hammam Chott     " },
                { label: " Hammam Ghezèze     ", value: "  Hammam Ghezèze     " },
                { label: " Hammam Lif     ", value: "  Hammam Lif     " },
                { label: " Hammam Sousse     ", value: "  Hammam Sousse     " },
                { label: " Hammamet     ", value: "  Hammamet     " },
                { label: " Hassi El Ferid     ", value: "  Hassi El Ferid     " },
                { label: " Hazeg Ellouza     ", value: "  Hazeg Ellouza     " },
                { label: " Hazoua     ", value: "  Hazoua     " },
                { label: " Hebira     ", value: "  Hebira     " },
                { label: " Hergla     ", value: "  Hergla     " },
                { label: " Hkaima     ", value: "  Hkaima     " },
                { label: " Jebiniana     ", value: "  Jebiniana     " },
                { label: " Jedelienne     ", value: "  Jedelienne     " },
                { label: " Jemmal     ", value: "  Jemmal     " },
                { label: " Jemna     ", value: "  Jemna     " },
                { label: " Jendouba     ", value: "  Jendouba     " },
                { label: " Jérissa     ", value: "  Jérissa     " },
                { label: " Jilma     ", value: "  Jilma     " },
                { label: " Joumine     ", value: "  Joumine     " },
                { label: " Kairouan     ", value: "  Kairouan     " },
                { label: " Kalâa Kebira     ", value: "  Kalâa Kebira     " },
                { label: " Kalâa Seghira     ", value: "  Kalâa Seghira     " },
                { label: " Kalâat el - Andalous     ", value: "  Kalâat el - Andalous     " },
                { label: " Kalâat Khasba     ", value: "  Kalâat Khasba     " },
                { label: " Kalaat Senan     ", value: "  Kalaat Senan     " },
                { label: " Kasserine     ", value: "  Kasserine     " },
                { label: " Kébili     ", value: "  Kébili     " },
                { label: " Kélibia     ", value: "  Kélibia     " },
                { label: " Kerkennah     ", value: "  Kerkennah     " },
                { label: " Kerker     ", value: "  Kerker     " },
                { label: " Kesra     ", value: "  Kesra     " },
                { label: " Khalidia     ", value: "  Khalidia     " },
                { label: " Khniss     ", value: "  Khniss     " },
                { label: " Kondar     ", value: "  Kondar     " },
                { label: " Korba     ", value: "  Korba     " },
                { label: " Korbous     ", value: "  Korbous     " },
                { label: " Ksar Hellal     ", value: "  Ksar Hellal     " },
                { label: " Ksibet el - Médiouni     ", value: "  Ksibet el - Médiouni     " },
                { label: " Ksibet Thrayet     ", value: "  Ksibet Thrayet     " },
                { label: " Ksour Essef     ", value: "  Ksour Essef     " },
                { label: " La Goulette     ", value: "  La Goulette     " },
                { label: " La Manouba     ", value: "  La Manouba     " },
                { label: " La Marsa     ", value: "  La Marsa     " },
                { label: " La Soukra     ", value: "  La Soukra     " },
                { label: " Lamta     ", value: "  Lamta     " },
                { label: " Le Bardo     ", value: "  Le Bardo     " },
                { label: " Le Kef     ", value: "  Le Kef     " },
                { label: " Le Kram     ", value: "  Le Kram     " },
                { label: " Le Sers     ", value: "  Le Sers     " },
                { label: " Lela     ", value: "  Lela     " },
                { label: " M'saken	                                                    ", value: "  M'saken	                                                    " },
                { label: " Mahdia     ", value: "  Mahdia     " },
                { label: " Mahrès     ", value: "  Mahrès     " },
                { label: " Majel Bel Abbès     ", value: "  Majel Bel Abbès     " },
                { label: " Makthar     ", value: "  Makthar     " },
                { label: " Mareth     ", value: "  Mareth     " },
                { label: " Mateur     ", value: "  Mateur     " },
                { label: " Matmata     ", value: "  Matmata     " },
                { label: " Mdhilla     ", value: "  Mdhilla     " },
                { label: " Médenine     ", value: "  Médenine     " },
                { label: " Medjez el - Bab     ", value: "  Medjez el - Bab     " },
                { label: " Mégrine     ", value: "  Mégrine     " },
                { label: " Meknassy     ", value: "  Meknassy     " },
                { label: " Melloulèche     ", value: "  Melloulèche     " },
                { label: " Menzel Abderrahmane     ", value: "  Menzel Abderrahmane     " },
                { label: " Menzel Bourguiba     ", value: "  Menzel Bourguiba     " },
                { label: " Menzel Bouzaiane     ", value: "  Menzel Bouzaiane     " },
                { label: " Menzel Bouzelfa     ", value: "  Menzel Bouzelfa     " },
                { label: " Menzel Chaker     ", value: "  Menzel Chaker     " },
                { label: " Menzel El Habib     ", value: "  Menzel El Habib     " },
                { label: " Menzel Ennour     ", value: "  Menzel Ennour     " },
                { label: " Menzel Fersi     ", value: "  Menzel Fersi     " },
                { label: " Menzel Hayet     ", value: "  Menzel Hayet     " },
                { label: " Menzel Horr     ", value: "  Menzel Horr     " },
                { label: " Menzel Jemil     ", value: "  Menzel Jemil     " },
                { label: " Menzel Kamel     ", value: "  Menzel Kamel     " },
                { label: " Menzel Mehiri     ", value: "  Menzel Mehiri     " },
                { label: " Menzel Salem     ", value: "  Menzel Salem     " },
                { label: " Menzel Temime     ", value: "  Menzel Temime     " },
                { label: " Messaadine     ", value: "  Messaadine     " },
                { label: " Métlaoui     ", value: "  Métlaoui     " },
                { label: " Metline     ", value: "  Metline     " },
                { label: " Métouia     ", value: "  Métouia     " },
                { label: " Mezzouna     ", value: "  Mezzouna     " },
                { label: " Mnihla     ", value: "  Mnihla     " },
                { label: " Mohamedia     ", value: "  Mohamedia     " },
                { label: " Moknine     ", value: "  Moknine     " },
                { label: " Monastir     ", value: "  Monastir     " },
                { label: " Mornag     ", value: "  Mornag     " },
                { label: " Mornaguia     ", value: "  Mornaguia     " },
                { label: " Moularès     ", value: "  Moularès     " },
                { label: " Nabeul     ", value: "  Nabeul     " },
                { label: " Nadhour     ", value: "  Nadhour     " },
                { label: " Nadhour Sidi Ali Ben Abed     ", value: "  Nadhour Sidi Ali Ben Abed     " },
                { label: " Nasrallah     ", value: "  Nasrallah     " },
                { label: " Nebeur     ", value: "  Nebeur     " },
                { label: " Nefta     ", value: "  Nefta     " },
                { label: " Nefza     ", value: "  Nefza     " },
                { label: " Nouvelle Matmata     ", value: "  Nouvelle Matmata     " },
                { label: " Ouabed Khazanet     ", value: "  Ouabed Khazanet     " },
                { label: " Ouchtata	                                                                   ", value: "  Ouchtata	                                                                   " },
                { label: " Oued Ellil     ", value: "  Oued Ellil     " },
                { label: " Oued Meliz     ", value: "  Oued Meliz     " },
                { label: " Ouerdanine     ", value: "  Ouerdanine     " },
                { label: " Oueslatia     ", value: "  Oueslatia     " },
                { label: " Ouled Chamekh     ", value: "  Ouled Chamekh     " },
                { label: " Ouled Haffouz     ", value: "  Ouled Haffouz     " },
                { label: " Radès     ", value: "  Radès     " },
                { label: " Raf Raf     ", value: "  Raf Raf     " },
                { label: " Raoued     ", value: "  Raoued     " },
                { label: " Ras Jebel     ", value: "  Ras Jebel     " },
                { label: " Redeyef     ", value: "  Redeyef     " },
                { label: " Regueb     ", value: "  Regueb     " },
                { label: " Rejiche     ", value: "  Rejiche     " },
                { label: " Remada     ", value: "  Remada     " },
                { label: " Rjim Maatoug     ", value: "  Rjim Maatoug     " },
                { label: " Rouhia     ", value: "  Rouhia     " },
                { label: " Sahline Moôtmar     ", value: "  Sahline Moôtmar     " },
                { label: " Sakiet Eddaïer     ", value: "  Sakiet Eddaïer     " },
                { label: " Sakiet Ezzit     ", value: "  Sakiet Ezzit     " },
                { label: " Sakiet Sidi Youssef     ", value: "  Sakiet Sidi Youssef     " },
                { label: " Saouaf     ", value: "  Saouaf     " },
                { label: " Sayada     ", value: "  Sayada     " },
                { label: " Sbeïtla     ", value: "  Sbeïtla     " },
                { label: " Sbiba     ", value: "  Sbiba     " },
                { label: " Sbikha     ", value: "  Sbikha     " },
                { label: " Sejnane     ", value: "  Sejnane     " },
                { label: " Sened     ", value: "  Sened     " },
                { label: " Sfax     ", value: "  Sfax     " },
                { label: " Sidi Aïch     ", value: "  Sidi Aïch     " },
                { label: " Sidi Ali Ben Aoun     ", value: "  Sidi Ali Ben Aoun     " },
                { label: " Sidi Alouane     ", value: "  Sidi Alouane     " },
                { label: " Sidi Ameur     ", value: "  Sidi Ameur     " },
                { label: " Sidi Bennour     ", value: "  Sidi Bennour     " },
                { label: " Sidi Bou Ali     ", value: "  Sidi Bou Ali     " },
                { label: " Sidi Bou Rouis     ", value: "  Sidi Bou Rouis     " },
                { label: " Sidi Bou Saïd     ", value: "  Sidi Bou Saïd     " },
                { label: " Sidi Bouzid     ", value: "  Sidi Bouzid     " },
                { label: " Sidi El Hani     ", value: "  Sidi El Hani     " },
                { label: " Sidi Hassine     ", value: "  Sidi Hassine     " },
                { label: " Sidi Ismail	                                                                  ", value: "  Sidi Ismail	                                                                  " },
                { label: " Sidi Thabet     ", value: "  Sidi Thabet     " },
                { label: " Sidi Zid     ", value: "  Sidi Zid     " },
                { label: " Siliana     ", value: "  Siliana     " },
                { label: " Skhira     ", value: "  Skhira     " },
                { label: " Slouguia	                                                                  ", value: "  Slouguia	                                                                  " },
                { label: " Soliman     ", value: "  Soliman     " },
                { label: " Somâa     ", value: "  Somâa     " },
                { label: " Souk Jedid     ", value: "  Souk Jedid     " },
                { label: " Souk Lahad     ", value: "  Souk Lahad     " },
                { label: " Sousse     ", value: "  Sousse     " },
                { label: " Tabarka     ", value: "  Tabarka     " },
                { label: " Tajerouine     ", value: "  Tajerouine     " },
                { label: " Takelsa     ", value: "  Takelsa     " },
                { label: " Tamerza     ", value: "  Tamerza     " },
                { label: " Tataouine     ", value: "  Tataouine     " },
                { label: " Tazarka     ", value: "  Tazarka     " },
                { label: " Téboulba     ", value: "  Téboulba     " },
                { label: " Teboulbou     ", value: "  Teboulbou     " },
                { label: " Tebourba     ", value: "  Tebourba     " },
                { label: " Téboursouk     ", value: "  Téboursouk     " },
                { label: " Testour     ", value: "  Testour     " },
                { label: " Thala     ", value: "  Thala     " },
                { label: " Thélepte     ", value: "  Thélepte     " },
                { label: " Thibar     ", value: "  Thibar     " },
                { label: " Thyna     ", value: "  Thyna     " },
                { label: " Tinja     ", value: "  Tinja     " },
                { label: " Tlelsa     ", value: "  Tlelsa     " },
                { label: " Touiref     ", value: "  Touiref     " },
                { label: " Touza     ", value: "  Touza     " },
                { label: " Tozeur     ", value: "  Tozeur     " },
                { label: " Tunis     ", value: "  Tunis     " },
                { label: " Utique     ", value: "  Utique     " },
                { label: " Zaghouan     ", value: "  Zaghouan     " },
                { label: " Zaouiet Djedidi     ", value: "  Zaouiet Djedidi     " },
                { label: " Zaouiet Kontoch     ", value: "  Zaouiet Kontoch     " },
                { label: " Zaouiet Sousse     ", value: "  Zaouiet Sousse     " },
                { label: " Zarat     ", value: "  Zarat     " },
                { label: " Zarzis     ", value: "  Zarzis     " },
                { label: " Zarzis Nord     ", value: "  Zarzis Nord     " },
                { label: " Zelba     ", value: "  Zelba     " },
                { label: " Zéramdine     ", value: "  Zéramdine     " },
                { label: " Zriba     ", value: "  Zriba     " },



            ],
            selectedCity: ''
        }
    }
    handelVille = () => {
        if (this.state.value) {
            console.log(this.state.value)
        }
    }

    handleChangeVille = (e) => {
        this.setState({ Ville: e.target.value })
    }
    render() {

        return (
            <div className="container">
                <Select options={this.state.list} onChange={this.handleChangeVille} onChange={(e) => { this.setState({ ...this.state, selectedCity: e.label }) }} className="" placeholder="Partout en Tunis" />
            </div>
        )
    }
}

export default LocationSearch